baseurl = "/"
languageCode = "en-us"
theme = "nivenly-theme"
paginate = 5

[params]
  # dir name of your blog content (default is `content/lib`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 10
  # Enable to show reading time in minutes for lib
  showReadingTime = false


[languages]
  [languages.en]
    description = "professional grown up business adult does important computer business :: professional computer adult :: famous transgender queer cyber hacker :: high alpine enthusiast"
    title = "nivenly.com"
    subtitle = "kris n贸va"
    keywords = "kris, kris nova, nova, n贸va, programming, linux, engineer, blog, archive, official, sexy"
    copyright = "2021 Kris N贸va"


# ----------------------------------------------------------
# Homepage Content
#

    [languages.en.params.home]
      title = "kris n贸va"
      content  = "the main body of the website"



# ----------------------------------------------------------
    [languages.en.params.logo]
      # [logoUser@logoHost]: /path >$
      logoUser = "nova"
      logoHost = "nivenly"



    [languages.en.menu]
    [[languages.en.menu.main]]
        identifier = "archive"
        name = "archive"
        url = "https://www.twitch.tv/krisnova/videos?filter=all&sort=time"
      [[languages.en.menu.main]]
        identifier = "readme"
        name = "readme"
        url = "/readme"
      [[languages.en.menu.main]]
        identifier = "src"
        name = "src"
        url = "/src"
      [[languages.en.menu.main]]
        identifier = "lib"
        name = "lib"
        url = "/lib"
      [[languages.en.menu.main]]
        identifier = "live"
        name = "live"
        url = "/live"
      [[languages.en.menu.main]]
        identifier = "contrib"
        name = "contrib"
        url = "/contrib"





