#
# --------------------------------------------------------------------------------------------------
#
#
#   /$$   /$$ /$$                               /$$
#  | $$$ | $$|__/                              | $$
#  | $$$$| $$ /$$ /$$    /$$ /$$$$$$  /$$$$$$$ | $$ /$$   /$$      /$$$$$$$  /$$$$$$  /$$$$$$/$$$$
#  | $$ $$ $$| $$|  $$  /$$//$$__  $$| $$__  $$| $$| $$  | $$     /$$_____/ /$$__  $$| $$_  $$_  $$
#  | $$  $$$$| $$ \  $$/$$/| $$$$$$$$| $$  \ $$| $$| $$  | $$    | $$      | $$  \ $$| $$ \ $$ \ $$
#  | $$\  $$$| $$  \  $$$/ | $$_____/| $$  | $$| $$| $$  | $$    | $$      | $$  | $$| $$ | $$ | $$
#  | $$ \  $$| $$   \  $/  |  $$$$$$$| $$  | $$| $$|  $$$$$$$ /$$|  $$$$$$$|  $$$$$$/| $$ | $$ | $$
#  |__/  \__/|__/    \_/    \_______/|__/  |__/|__/ \____  $$|__/ \_______/ \______/ |__/ |__/ |__/
#                                                   /$$  | $$
#                                                  |  $$$$$$/
#                                                   \______/
#
#
# Nóva you have put some fucking time into this. Trust yourself.

baseurl = "/"
languageCode = "en-us"
theme = "nivenly-theme"
paginate = 5
enableRobotsTXT = true


#
# ---------------------------------------------------------------
#
#   /$$$$$$   /$$$$$$   /$$$$$$  /$$$$$$  /$$$$$$/$$$$   /$$$$$$$
#  /$$__  $$ |____  $$ /$$__  $$|____  $$| $$_  $$_  $$ /$$_____/
# | $$  \ $$  /$$$$$$$| $$  \__/ /$$$$$$$| $$ \ $$ \ $$|  $$$$$$
# | $$  | $$ /$$__  $$| $$      /$$__  $$| $$ | $$ | $$ \____  $$
# | $$$$$$$/|  $$$$$$$| $$     |  $$$$$$$| $$ | $$ | $$ /$$$$$$$/
# | $$____/  \_______/|__/      \_______/|__/ |__/ |__/|_______/
# | $$
# | $$
# |__/
#
#
# Here is where the dynamic interpolating happens.
#
# We have "Upgradde"d hugo (Two D's for a Double-Dose of pimping).
#
# This is where we can mapp the interpolation with Hugo, to the
# Interpolation with the Go runtime.
# Basically set a key equal to what you want to pull from the
# Nivenly "app" (which runs with bjorno) here. Then you can access
# the value dynamically in the page elsewhere.
#
# Nóva: Try to only use the bjorno runtime params here. For everything
#       else try to define above as a site vairable {{ $.Site.Key }}
[params]
  # Example Param:
  #
  # key = "value"
  # {{ $.Site.Params.Key }}

  remoteAddress = "{{ .Client.Addr }}"
  requestString = "{{ .R.Method }} {{ .R.URL.Path }} {{ .R.Proto }}"
  aboutYouString = "{{ .Client.ClientString }} "



[languages]
  [languages.en]
    description = "professional computer adult :: famous transgender queer cyber hacker :: high alpine enthusiast"
    title = "nivenly.com"
    subtitle = "kris nóva"
    keywords = "kris, kris nova, nova, nóva, programming, linux, engineer, blog, archive, official, sexy, nivenly, homepage, wepage, important, serious, iron clad, professional, adult, business, computer, tech, books, author, author, super nóva, supernova, github, freebsd, mountains, speaker, public, public speaker, twitch, stream, stream stream, live, nova"
    copyright = "2021 Kris Nóva"

# ----------------------------------------------------------
    [languages.en.params.logo]
      logoUser = "nova"
      logoHost = "nivenly"

    [languages.en.menu]
    [[languages.en.menu.main]]
        identifier = "archive"
        name = "archive"
        url = "https://www.youtube.com/channel/UCRvH2UexTzcbZRwCS6OxJ3w"
      [[languages.en.menu.main]]
        identifier = "readme"
        name = "readme"
        url = "/readme"
      [[languages.en.menu.main]]
        identifier = "src"
        name = "src"
        url = "https://github.com/kris-nova/nivenly.com"
      [[languages.en.menu.main]]
        identifier = "lib"
        name = "lib"
        url = "/lib"
      [[languages.en.menu.main]]
        identifier = "live"
        name = "live"
        url = "/live"
      [[languages.en.menu.main]]
        identifier = "contrib"
        name = "contrib"
        url = "/contrib"
      [[languages.en.menu.main]]
        identifier = "questions"
        name = "questions"
        url = "/questions"
